FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

WORKDIR /app

COPY requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt \
    && pip install "papermill[s3]" ipykernel nbformat

COPY . /app

ENV JOB_JSON=""
ENV JOB_JSON_FILE=""

CMD ["python", "/app/run_from_json.py"]

# input json example:
# {
#   "notebook_out": "s3://my-bucket/some/path/run.executed.ipynb",
#   "params": {
#     "param_feature_name": "perc_95_normalized_height",
#     "param_n_tiles_side": 512
#   }
# }