name: Deploy FastAPI and Batch Image
on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ECR_REGISTRY: ""  # set after login step below
      ECR_REPOSITORY: notebook2rest
      # NOTEBOOK_NAME: notebook
    steps:
      - name: Checkout Code  
        uses: actions/checkout@v4

      - name: Configure AWS Credentials  
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: eu-west-1
      
      - name: Verify Identity  
        run: aws sts get-caller-identity

      - name: Zip and Deploy Lambda
        run: |
          (cd lambda-build && zip -r ../function.zip .) && (cd lambda && zip -r ../function.zip .) && zip function.zip app.py
          aws lambda update-function-code \
            --function-name notebook2rest \
            --zip-file fileb://function.zip
