name: Deploy FastAPI and Batch Image
on:
  push:
    branches: [ main ]

permissions:
  id-token: write   # Required for OIDC
  contents: read    # Required to checkout code

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Read the code from the repository
      - name: Checkout Code  
        uses: actions/checkout@v4

      # Use OIDC to get AWS credentials
      - name: Configure AWS Credentials  
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: eu-west-1
      
      # Just to confirm the OIDC setup is working
      - name: Verify Identity  
        run: aws sts get-caller-identity

    #   # --- PART 1: BUILD & PUSH DOCKER IMAGE ---
    #   - name: Login to Amazon ECR
    #     id: login-ecr
    #     uses: aws-actions/amazon-ecr-login@v2

    #   - name: Build, Tag, and Push Image to ECR
    #     env:
    #       ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
    #       ECR_REPOSITORY: my-batch-image-repo
    #       IMAGE_TAG: latest # Or ${{ github.sha }} if using Immutable tags
    #     run: |
    #       # Here is where you'd run your script to convert Notebook -> Dockerfile
    #       docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
    #       docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      # --- PART 2: SYNC FASTAPI TO LAMBDA ---
      
      # Push app.py from repo root to Lambda
      - name: Zip and Deploy Lambda
        run: |
          zip -r function.zip api_repo 
          aws lambda update-function-code \
            --function-name notebook2rest \
            --zip-file fileb://function.zip
